# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{xupa_emec}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bernardo de P\303\241dua"]
  s.date = %q{2010-12-01}
  s.default_executable = %q{xupa_emec}
  s.description = %q{Puxa dados sobre instituições de ensino superior do site do MEC para o formato CSV.}
  s.email = %q{berpasan@gmail.com}
  s.executables = ["xupa_emec"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "bin/xupa_emec",
    "lib/xupa_emec.rb",
    "lib/xupa_emec/crawler.rb",
    "lib/xupa_emec/version.rb",
    "test/helper.rb",
    "test/test_xupa_emec.rb",
    "xupa_emec.gemspec"
  ]
  s.homepage = %q{http://github.com/bernardo/xupa_emec}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Puxa dados sobre instituições de ensino superior do site do MEC para o formato CSV.}
  s.test_files = [
    "test/helper.rb",
    "test/test_xupa_emec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mechanize>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<trollop>, [">= 0"])
      s.add_runtime_dependency(%q<fastercsv>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0"])
      s.add_runtime_dependency(%q<mechanize>, ["~> 1.0"])
      s.add_runtime_dependency(%q<trollop>, ["~> 1.16"])
      s.add_runtime_dependency(%q<fastercsv>, ["~> 1.5"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4"])
    else
      s.add_dependency(%q<mechanize>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<trollop>, [">= 0"])
      s.add_dependency(%q<fastercsv>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<activesupport>, ["~> 3.0"])
      s.add_dependency(%q<mechanize>, ["~> 1.0"])
      s.add_dependency(%q<trollop>, ["~> 1.16"])
      s.add_dependency(%q<fastercsv>, ["~> 1.5"])
      s.add_dependency(%q<nokogiri>, ["~> 1.4"])
    end
  else
    s.add_dependency(%q<mechanize>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<trollop>, [">= 0"])
    s.add_dependency(%q<fastercsv>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<activesupport>, ["~> 3.0"])
    s.add_dependency(%q<mechanize>, ["~> 1.0"])
    s.add_dependency(%q<trollop>, ["~> 1.16"])
    s.add_dependency(%q<fastercsv>, ["~> 1.5"])
    s.add_dependency(%q<nokogiri>, ["~> 1.4"])
  end
end

